### ISSUE TITLE
Error Activating Custom-API

### ISSUE THREAD

**Issue by luzadev** [vivmagarwal/strapi-plugin-custom-api-builder#1]
Hi,
after setting all information on file plugin.js when launch this command: yarn build, I get this error: 
Error: ./src/plugins/custom-api couldn't be resolved

**Comment by roganoalien** [comment]
Has this issue been solved? I've just tried the plugin and have the same issue

**Comment by luzadev** [comment]
Thanks. Now its ok!

**Comment by luzadev** [comment]
Thanks...Now its ok!
