### ISSUE TITLE
When deleting an api it shows a dialog saying "Add functionality to delete the API"

### ISSUE THREAD

**Issue by ayush-parida** [vivmagarwal/strapi-plugin-custom-api-builder#13]
@vivmagarwal When deleting an api it shows a dialog saying "Add functionality to delete the API" and there are no instructions available for how to perform the same. Also uninstalling the plugin is not a choice as it breaks multiple things.

**Comment by vivmagarwal** [comment]
True @AllPlayer 
I intend to take this up in the upcoming weekend.

**Comment by AllPlayer** [comment]
@vivmagarwal 
The issue could be bypassed by disabling the plugin from the plugins.js for the project to remove it but, re-enabling it will again cause it to crash.
